edited readme better

diff --git a/install_server b/install_server
--- a/install_server
+++ b/install_server
@@ -25,6 +25,22 @@ then
   rm ./install_server
   exit
 fi
+#if ! command -v ufw &> /dev/null
+#then
+#  echo "ERROR! -- Cannot find valid ufw installation. Please make sure it is installed."
+#  rm server -rf
+#  rm server_backup -rf
+#  rm ./install_server
+#  exit
+#fi
+if ! command -v firewall-cmd &> /dev/null
+then
+  echo "ERROR! -- Cannot find valid firewall-cmd installation. Please make sure it is installed."
+  rm server -rf
+  rm server_backup -rf
+  rm ./install_server
+  exit
+fi
 read -p "What would you like to name this server instance: " session
 if [ -z "$session" ]
 then
