edited bug with headless backup

diff --git a/server/scripts/backup_s_server b/server/scripts/backup_s_server
--- a/server/scripts/backup_s_server
+++ b/server/scripts/backup_s_server
@@ -6,7 +6,14 @@ destination="destination_placeholder"
 echo "Server Backup Script"
 echo "Name: $s"
 echo "Minecraft Version: $v"
-./stop_server
+tmux has-session -t $s 2>/dev/null
+if [ $? != 0 ]; then
+  echo "ERROR! -- Server Not Running!"
+  exit
+fi
+tmux send-keys -t $s 'stop' C-m
+tmux attach -t $s
+echo "$v Server Shutdown"
 sleep 45
 find ../../${destination} -mtime +14 -type d -exec rm -r {} \;
 date="$(date +"%d-%m-%Y")"
